spring.application.name=EcomApplication
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/nonsyncbobbal
spring.datasource.username=nonsyncbobbal
spring.datasource.password=Bablu@456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true